<template>
  <div class="login">
    <div class="login__header">
      <div class="login__logo">
        <img src="../assets/logo-img.png" alt="logo" height="110px" />
      </div>
      <div class="login__heading">
        <h2 class="login__heading__head">Login</h2>
        <p class="login__heading__para">FilmBase</p>
      </div>
    </div>
    <div class="login__main">
      <div class="login__container">
        <button class="login__btn">Login</button>
        <button class="login__btn">Browse as Guest</button>
        <p class="login__para">Guest users have access to limited features</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style></style>
